### ISSUE TITLE
Query Params

### ISSUE THREAD

**Issue by mixonic** [stefanpenner/ember-strict-resolver#11]
I don't yet have an isolated reproduction, but it seems query params don't appear in `{{link-to` generated URLs.

**Comment by tmquinn** [comment]
Hmm... I just tried
```hbs
{{#link-to "with-query-params" (query-params foo="foo" bar="bar")}}Go to foo-bar{{/link-to}}
```
in the dummy app and it worked, although I did upgrade ember first...

**Comment by mixonic** [comment]
👍 thank @tmquinn for the attempted repro. I'll close this based on your experience and re-open once I can narrow this down.
