### ISSUE TITLE
[bug] variables in templates are being normalized as helpers

### ISSUE THREAD

**Issue by gabrielcsapo** [stefanpenner/ember-strict-resolver#28]
The following code results in `helpers:fooBar`:

```hbs
<div>
   {{fooBar}}
</div>
```

Since this is not a helper the fix would be:

```hbs
<div>
   {{this.fooBar}}
</div>
```

But as it is inevitable that packages will not being using explicit this, what would be the right way to guard against this?

**Comment by rwjblue** [comment]
The upstream ember-resolver specifically avoids normalizing / dasherizing helpers / components / modifiers for this exact reason (but in reverse): using `{{fooBar}}` should **not** attempt to look up `helper:foo-bar`.

I'm not 100% sure what you are seeing here, but looking for `helper:fooBar` should just fail, and then you'd get a normal local property lookup.

**Comment by gabrielcsapo** [comment]
@rwjblue yes this is what I am trying to do locally with a fork of strict resolver. I think potentially removing the assert that enforces dasherized values and letting the internal looks fail to resolve might be the best move forward. 

Right now if the above mentioned helper comes into the resolve method it fast fails with the assert.

**Comment by rwjblue** [comment]
Yeah, I think the assertion needs to be a bit smarter. We should assert that we shouldn't require normalization for something that doesn't **actually** use normalization. 😛

**Comment by gabrielcsapo** [comment]
I agree!
