### ISSUE TITLE
warning / assertion in dev mode for values that need normalization

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/ember-strict-resolver#3]
https://github.com/stefanpenner/ember-strict-resolver/blob/master/addon/index.js#L19

**Comment by gabrielcsapo** [comment]
What would need to be done to add this?

**Comment by stefanpenner** [comment]
@gabrielcsapo hmm, I don't really remember actually...

**Comment by gabrielcsapo** [comment]
going to close this for now
